#!/bin/bash

# export the location of the phytoStreams database
export PHYTOPORTS_DB_FILE=~/phytoMorphTK/dataBaseFiles/dataPorts.db
# export the location of the phytoStreams for future 
echo 'export PHYTOPORTS_DB_FILE=~/phytoMorphTK/dataBaseFiles/dataPorts.db' >> ~/.bashrc
