#!/bin/bash 
# create the ports table 
# id is the primary key and the unique device name
# busport text is a field for information about the busport
# busport field is the computers name for the port
sqlite3 $PHYTOPORTS_DB_FILE "CREATE TABLE IF NOT EXISTS ports (id INTEGER PRIMARY KEY,busport TEXT,UNIQUE (busport),busy BOOLEAN DEFAULT 0);"
