#!/bin/bash
# last edited Jan, 02 2020 - changed to system variable for location of database
busPortList=$(sqlite3 $PHYTOPORTS_DB_FILE ".separator ","" "select busport from ports";)
for i in $(echo ${busPortList} | sed "s/,/ /g")
    do
	dev=$(usb_port_2_device $i)
	echo "busPort:$i --> device:$dev"
    done
