#!/bin/bash
# 19_12_16 - This command will take a user through the process of setting up scaners by 
# prompting the user to plug in and hit key.  The method uses a diff command between the
# outputs of usb-devices command written to file.
# commented out below line > 19_12_16
#lsusb | sed -e 's/Bus \([0-9]\+\) Device \([0-9]\+\).*/\1:\2/g' > pre.txt
# write out the report from usb-devices
usb-devices | grep T: > pre.txt


