#!/bin/bash
# last edited on Jan, 02 2020 - mod the relative pathing ./ to absolute 
echo "Port Menu."
echo "Please select one."
echo "[0] Add Port to bank."
echo "[1] Remove Port from bank."
echo "[2] Test Port bank."
echo "[3] List Ports." 
echo "[4] Quit."
read selection
case $selection in
	0)
		addPort
		portBankMenu
		;;
	1)
		removePorts
		portBankMenu
		;;
	2)
		checkPorts
		portBankMenu
		;;
	3)
		listPorts
		;;	
	4)
		;;

	*)
		echo "Invalid selection"
		;;
esac
