#!/bin/bash
#1 := program - the program using the stream
#2 := mode/type - cyverseBuffer xor cyverseStream
#3 := number - the unique number for the stream
#4 := file to stream - file to stream to cyverse of buffer
programName=$1 
streamType=$2
streamNumber=$3
streamFile=$4
# get the file name from the fullpath+filename
filename="${streamFile##*/}"
# get the basename by removing the file name from the string
basename="${streamFile%$filename}"
# find the file - whole path
#streamFile=$(find $(pwd -P) -type f -name "$filename")
echo "################################"
echo "starting file stream: $streamFile"
echo "gathering stream information:"
streamTarget=$(sqlite3 $PHYTOSTREAMS_DB_FILE "select target from streams WHERE program='$programName' AND active=1 AND number=$streamNumber AND mode='$streamType'";)
streamSource=$(sqlite3 $PHYTOSTREAMS_DB_FILE "select source from streams WHERE program='$programName' AND active=1 AND number=$streamNumber AND mode='$streamType'";)
# the source is the base source - then the extra path is the full - base source 
extraPath=${streamFile#$streamSource}
# remove the file name from the extra path too
extraPath=${extraPath%$filename}
echo "------------------------------"
echo "fileName:"$filename
echo "extraPath:$extraPath"
echo "streamSource:$streamSource"
echo "streamTarget:"$streamTarget$extraPath
echo "pushing: $streamFile -->" $streamTarget
echo "------------------------------"
if [ "$streamType" = 'cyverseStream' ]
then
	# call phytoCP
	phytoCP cyverse $streamFile $streamTarget$extraPath $filename
elif [ "$streamType" = 'cyverseBuffer' ] 
then
	phytoCP local $streamFile $streamTarget$extraPath $filename
	sqlite3 $PHYTOSTREAMS_DB_FILE "INSERT OR IGNORE INTO fileQueue (program,mode,number,file,isQueued) VALUES ('$programName','$streamType"_out"',$streamNumber,'$streamTarget$extraPath$filename',1);"
fi
echo "ended file stream."
echo "################################"
