#!/bin/bash
fileName=$1
fvc=$(./find_kvp dvc $1)
if [ "$fvc" != "NotFound" ]
then
	
	v=$(./getValue $dvc)
	LEN=${#v}
	LEN=$(($LEN-2))
	type=${v:0:2}
	fhash=${v:2:$LEN}

	# hash the file for check
	case $type in
		s-)
		hash=$(./genHash sha256 $fileName)
		;;		
		m-)
		hash=$(./genHash md5 $fileName)
		;;	
	esac

	# report file check
	if [ "$hash" == "$fhash" ]
	then
		echo "{file_1}"
	else
		echo "{file_0}"
	fi

fi

