#!/bin/bash 
mkdir -p ~/phytoMorphTK/dataBaseFiles/
# streams table
sqlite3 $PHYTOSTREAMS_DB_FILE "CREATE TABLE IF NOT EXISTS streams (id INTEGER PRIMARY KEY,program TEXT, mode TEXT,number INTEGER,active INTEGER, target TEXT, source TEXT, createDate TEXT, UNIQUE (program,mode,number));"
# file queue table
sqlite3 $PHYTOSTREAMS_DB_FILE "CREATE TABLE IF NOT EXISTS fileQueue (id INTEGER PRIMARY KEY, program TEXT, mode TEXT, number INTEGER, file TEXT,isQueued INTEGER);"
# job table
sqlite3 $PHYTOSTREAMS_DB_FILE "CREATE TABLE IF NOT EXISTS jobQueue (id INTEGER PRIMARY KEY, program TEXT, file TEXT, isQueued INTEGER);"
