#!/bin/bash
sel=$1
fileName=$2
#read fileName
N=${#fileName}
G=${fileName//\}/}
G=${#G}
nd=$(($N-$G))
dateSep='~'
nfileName=''
length=$(($N-1))
runningSum=0
cnt=0
kvpList=()
curIndex=0
ret="NotFound"
for index in $(seq 0 1 $length)
	do

	letter=${fileName:index:1}

	# detected opening
	if [ "$letter" == "{" ]
	then
		runningSum=$(($runningSum-1))
	fi

	# detected closing
	if [ "$letter" == "}" ]
	then
		runningSum=$(($runningSum+1))
	fi

	# detected even sum game
	if [ "$runningSum" -eq "0" ]
	then
		if [ "$index" -ne "0" ]
		then
			curLength=$(($index-$curIndex+1))
			curKVP=${fileName:$curIndex:$curLength}
			k=$(echo $curKVP | getKey)
			if [ "$k" == "$sel" ]
			then
				ret=$curKVP
			fi

			kvpList+=( $curKVP )
			curIndex=$(($index+1))

			(( cnt++ ))
		fi	
	fi

done

echo $ret

