#!/bin/bash
echo "***************************************************"
echo "* 	Phytomorph Metadata Menu		*"
echo "***************************************************"
echo " Please select one:"
echo "[1] - Generate Metadata tile strips for device bank"
echo "[2] - Generate QR labels"
echo "[3] - Generate QR sheets for plant profiler"

